development:
  servers: ["localhost:9160"]
  keyspace: "datastax_rails_development"
  strategy_class: "org.apache.cassandra.locator.SimpleStrategy"
  strategy_options: {"DC1": "1"} 
  replication_factor: 1
  solr:
    url: http://localhost:8983/solr
    
test:
  servers: ["localhost:9160"]
  keyspace: "datastax_rails_test"
  strategy_class: "org.apache.cassandra.locator.NetworkTopologyStrategy"
  strategy_options: {"DC1": "1"} 
  replication_factor: 1
  solr:
    url: http://localhost:8983/solr
        
