productiont:
  servers: ["127.0.0.1:9160"]
  keyspace: "datastax_rails_development"
  strategy_options: {"RS": "3"}
  connection_options:
    timeout: 20
    retries: 3
    server_max_requests: 1000
  solr:
    port: 8983
    path: /solr

development:
  servers: ["127.0.0.1:9160"]
  keyspace: "datastax_rails_development"
  strategy_class: "org.apache.cassandra.locator.SimpleStrategy"
  strategy_options: {"replication_factor": "1"}
  connection_options:
    timeout: 10
  solr:
    port: 8983
    path: /solr
    
test:
  servers: ["127.0.0.1:9160"]
  keyspace: "datastax_rails_test"
  strategy_class: "org.apache.cassandra.locator.SimpleStrategy"
  strategy_options: {"replication_factor": "1"}
  connection_options:
    timeout: 30
  solr:
    port: 8983
    path: /solr
